### ISSUE TITLE
Fix problem with encrypted environment variables for PR from fork

### ISSUE THREAD

**Issue by ondrejtomas** [IBM/watson-assistant-workbench#25]
PR from fork failed because encrypted environment variables are not available for this builds, see https://docs.travis-ci.com/user/environment-variables/

**Comment by ondrejtomas** [comment]
Interesting article about this problem: https://blog.algolia.com/travis-encrypted-variables-external-contributions/

It seems that there is no easy solution how to do it... because for our testing we need credentials with write access to WA (to deploy workspace and test it) and somebody from outside could rewrite travis.yml to steal our credentials or attack WA by multiply requests (could cause DoS) and that could cost us something (API calls).

**Comment by ondrejtomas** [comment]
Related: https://github.com/travis-ci/travis-ci/issues/6112

**Comment by ondrejtomas** [comment]
After internal discussion we realized that we cannot allow to anybody from outside to run Travis CI without our code check before because it can contain changes that break CI or delete github repository.

**Comment by blowfishpro** [comment]
Certainly allowing any external pull request to access encrypted variables could open up some security holes.  But it's also useful to have CI be able to run against external pull requests before merging them, which also sometimes requires use of those encrypted variables.

Would it be reasonable to allow external PR builds to access encrypted variables after they have been approved by a project member on Github (perhaps as a per-project setting in case some don't want this)?  That would make it so that a real person can inspect the code for any potential security issues before CI runs, but still have the confidence of CI running before merging.

**Comment by ondrejtomas** [comment]
We decided to create lite instance of WA and provide its credential in Travis CI to be able to run PR from fork. Slack and Artifactory remain disable. We are aware of possible problems.
