### ISSUE TITLE
Change parameter VERBOSE to switch on log levels

### ISSUE THREAD

**Issue by ondrejtomas** [IBM/watson-assistant-workbench#266]
=> you can consider using different flag

**Comment by AlexejPopovic** [comment]
From now on, the logger verbosity and logger level will not be configurable in the WAW config files. The reason is that the config loader class uses the logger as well and it already needs to be set up upon loading. Verbosity will be only CLI flag, log level will be CLI argument as well as an option in the logger config file.

**Comment by AlexejPopovic** [comment]
Merged to devel, closing.
